version: '3.8'

services:
  pool:
    build: .
    ports:
      - "3333:3333"

    volumes:
      # Mount your asicseer config (this file must exist)
      - ./asicseer-pool.conf:/asicseer/asicseer-pool.conf:ro

      # Optional: directory to collect logs
      - ./pool-logs:/asicseer/logs

    command:
      - /usr/bin/asicseer-pool
      - -l
      - "7"
      - -B
      - -k
      - -L
      - -c
      - /asicseer/asicseer-pool.conf

    restart: unless-stopped
